### ISSUE TITLE
gwasm-dispatcher license

### ISSUE THREAD

**Issue by Macil** [golemfactory/gwasm-runner#46]
Is gwasm-dispatcher meant to be covered by the GPLv3 LICENSE file in the root of the repo? If it's GPLv3 and if including gwasm-dispatcher is necessary to make a webassembly binary that runs on Golem, then I believe any webassembly binaries submitted to Golem using it would need to have their whole source be open and be GPLv3, which I'm assuming is not intended. Using a more permissive license like MIT or Apache 2 specifically for the part that people build into their wasm binaries would avoid this.

**Comment by tworec** [comment]
Good point. We will change the `gwasm-dispatcher` license to LGPL.
